apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recipe-book-app4
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ilaysb1/Recipe-Book
    targetRevision: feature-finalproj-1
    path: ./proj-helm  # Path within your repo to the helm chart.
    helm:
      parameters:
        - name: image.repository  # Assuming your Helm values use this key
          value: ilaysb/final-project-1-flask_app
        - name: image.tag  # Assuming your Helm values use this key
          value: latest
        - name: image.pullPolicy  # Ensure your Helm chart supports this parameter
          value: Always
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true