additionalPrometheusRulesMap:
  rule-name:
    groups:
      - name: project
        rules:
          - alert: LowRunningPodsCount
            expr: count(kube_pod_status_phase{namespace="dev", pod=~"recipe-book-app5.*", phase="Running"}) < 3
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Low number of running pods"
              description: "The count of running pods matching 'recipe-book-app5*' in namespace 'dev' is below 3."
          - alert: HighCPUUsage
            expr: sum(rate(container_cpu_usage_seconds_total{namespace="dev", pod=~"recipe-book-app5.*"}[5m])) / count(kube_pod_container_status_running{namespace="dev", pod=~"recipe-book-app5.*"}) > 0.8
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage"
              description: "CPU usage in pods matching 'recipe-book-app5*' in namespace 'dev' is above 80%."
          - alert: HighMemoryUsage
            expr: (sum(container_memory_working_set_bytes{namespace="dev", pod=~"recipe-book-app5.*"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace="dev", pod=~"recipe-book-app5.*"})) * 100 > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage"
              description: "Memory usage in pods matching 'recipe-book-app5*' in namespace 'dev' is above 80% of the allocated limit."
