# Use the official Python image as a base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY test_app.py main.py run_tests.sh .env ./
COPY templates/ templates/
COPY requirements.txt ./

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x run_tests.sh

# Run the Flask application
# CMD ["./run_tests.sh"]

CMD ["sh", "-c", "python main.py & sleep 5 && python -m pytest test_app.py"]
