version: '3'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb+srv://ilaysb:Ilaysb12@cluster0.f1l3dro.mongodb.net/testDB  # Connection URI to MongoDB
    volumes:
      - ./main.py:/app/main.py   # Mount the main.py file
      - ./static:/app/static     # Mount the static directory
      
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    environment:
      MONGO_URI: mongodb+srv://ilaysb:Ilaysb12@cluster0.f1l3dro.mongodb.net/testDB  # Connection URI to MongoDB
    depends_on:
      - mongo
      - flask_app

volumes:
  mongodb_data:



