apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    io.kompose.service: flask-app
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: flask-app
