apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    io.kompose.service: mongo
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
